# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
namespace eval ::optrace {
  variable script "/home/swaggo/Code/Fag/fag_project_tests/vivado/NexysA7Game/NexysA7Game.runs/synth_1/Top.tcl"
  variable category "vivado_synth"
}

# Try to connect to running dispatch if we haven't done so already.
# This code assumes that the Tcl interpreter is not using threads,
# since the ::dispatch::connected variable isn't mutex protected.
if {![info exists ::dispatch::connected]} {
  namespace eval ::dispatch {
    variable connected false
    if {[llength [array get env XILINX_CD_CONNECT_ID]] > 0} {
      set result "true"
      if {[catch {
        if {[lsearch -exact [package names] DispatchTcl] < 0} {
          set result [load librdi_cd_clienttcl[info sharedlibextension]] 
        }
        if {$result eq "false"} {
          puts "WARNING: Could not load dispatch client library"
        }
        set connect_id [ ::dispatch::init_client -mode EXISTING_SERVER ]
        if { $connect_id eq "" } {
          puts "WARNING: Could not initialize dispatch client"
        } else {
          puts "INFO: Dispatch client connection id - $connect_id"
          set connected true
        }
      } catch_res]} {
        puts "WARNING: failed to connect to dispatch server - $catch_res"
      }
    }
  }
}
if {$::dispatch::connected} {
  # Remove the dummy proc if it exists.
  if { [expr {[llength [info procs ::OPTRACE]] > 0}] } {
    rename ::OPTRACE ""
  }
  proc ::OPTRACE { task action {tags {} } } {
    ::vitis_log::op_trace "$task" $action -tags $tags -script $::optrace::script -category $::optrace::category
  }
  # dispatch is generic. We specifically want to attach logging.
  ::vitis_log::connect_client
} else {
  # Add dummy proc if it doesn't exist.
  if { [expr {[llength [info procs ::OPTRACE]] == 0}] } {
    proc ::OPTRACE {{arg1 \"\" } {arg2 \"\"} {arg3 \"\" } {arg4 \"\"} {arg5 \"\" } {arg6 \"\"}} {
        # Do nothing
    }
  }
}

OPTRACE "synth_1" START { ROLLUP_AUTO }
set_param general.usePosixSpawnForFork 1
set_param xicom.use_bs_reader 1
set_param chipscope.maxJobs 3
set_msg_config  -id {Power 33-332}  -string {{WARNING: [Power 33-332] Found switching activity that implies high-fanout reset nets being asserted for excessive periods of time which may result in inaccurate power analysis.
Resolution: To review and fix problems, please run Power Constraints Advisor in the GUI from Tools > Power Constraints Advisor or run report_power with the -advisory option to generate a text report.}}  -suppress 
OPTRACE "Creating in-memory project" START { }
create_project -in_memory -part xc7a100tcsg324-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir /home/swaggo/Code/Fag/fag_project_tests/vivado/NexysA7Game/NexysA7Game.cache/wt [current_project]
set_property parent.project_path /home/swaggo/Code/Fag/fag_project_tests/vivado/NexysA7Game/NexysA7Game.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_output_repo /home/swaggo/Code/Fag/fag_project_tests/vivado/NexysA7Game/NexysA7Game.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
OPTRACE "Creating in-memory project" END { }
OPTRACE "Adding files" START { }
read_mem {
  /home/swaggo/Code/Fag/fag_project_tests/memory_init/sprite_init_114.mem
  /home/swaggo/Code/Fag/fag_project_tests/memory_init/sprite_init_56.mem
  /home/swaggo/Code/Fag/fag_project_tests/memory_init/backtile_init_29.mem
  /home/swaggo/Code/Fag/fag_project_tests/memory_init/sprite_init_9.mem
  /home/swaggo/Code/Fag/fag_project_tests/memory_init/backtile_init_1.mem
  /home/swaggo/Code/Fag/fag_project_tests/memory_init/sprite_init_13.mem
  /home/swaggo/Code/Fag/fag_project_tests/memory_init/sprite_init_106.mem
  /home/swaggo/Code/Fag/fag_project_tests/memory_init/sprite_init_99.mem
  /home/swaggo/Code/Fag/fag_project_tests/memory_init/sprite_init_48.mem
  /home/swaggo/Code/Fag/fag_project_tests/memory_init/sprite_init_21.mem
  /home/swaggo/Code/Fag/fag_project_tests/memory_init/sprite_init_90.mem
  /home/swaggo/Code/Fag/fag_project_tests/memory_init/backtile_init_10.mem
  /home/swaggo/Code/Fag/fag_project_tests/memory_init/sprite_init_0.mem
  /home/swaggo/Code/Fag/fag_project_tests/memory_init/sprite_init_64.mem
  /home/swaggo/Code/Fag/fag_project_tests/memory_init/sprite_init_74.mem
  /home/swaggo/Code/Fag/fag_project_tests/memory_init/sprite_init_31.mem
  /home/swaggo/Code/Fag/fag_project_tests/memory_init/sprite_init_104.mem
  /home/swaggo/Code/Fag/fag_project_tests/memory_init/sprite_init_82.mem
  /home/swaggo/Code/Fag/fag_project_tests/memory_init/backtile_init_3.mem
  /home/swaggo/Code/Fag/fag_project_tests/memory_init/sprite_init_122.mem
  /home/swaggo/Code/Fag/fag_project_tests/memory_init/sprite_init_120.mem
  /home/swaggo/Code/Fag/fag_project_tests/memory_init/tone_init_6.mem
  /home/swaggo/Code/Fag/fag_project_tests/memory_init/sprite_init_7.mem
  /home/swaggo/Code/Fag/fag_project_tests/memory_init/sprite_init_84.mem
  /home/swaggo/Code/Fag/fag_project_tests/memory_init/sprite_init_97.mem
  /home/swaggo/Code/Fag/fag_project_tests/memory_init/sprite_init_116.mem
  /home/swaggo/Code/Fag/fag_project_tests/memory_init/sprite_init_70.mem
  /home/swaggo/Code/Fag/fag_project_tests/memory_init/backtile_init_14.mem
  /home/swaggo/Code/Fag/fag_project_tests/memory_init/sprite_init_23.mem
  /home/swaggo/Code/Fag/fag_project_tests/memory_init/backtile_init_27.mem
  /home/swaggo/Code/Fag/fag_project_tests/memory_init/sprite_init_66.mem
  /home/swaggo/Code/Fag/fag_project_tests/memory_init/sprite_init_79.mem
  /home/swaggo/Code/Fag/fag_project_tests/memory_init/sprite_init_38.mem
  /home/swaggo/Code/Fag/fag_project_tests/memory_init/backtile_init_8.mem
  /home/swaggo/Code/Fag/fag_project_tests/memory_init/sprite_init_36.mem
  /home/swaggo/Code/Fag/fag_project_tests/memory_init/sprite_init_102.mem
  /home/swaggo/Code/Fag/fag_project_tests/memory_init/sprite_init_68.mem
  /home/swaggo/Code/Fag/fag_project_tests/memory_init/sprite_init_72.mem
  /home/swaggo/Code/Fag/fag_project_tests/memory_init/sprite_init_5.mem
  /home/swaggo/Code/Fag/fag_project_tests/memory_init/sprite_init_41.mem
  /home/swaggo/Code/Fag/fag_project_tests/memory_init/sprite_init_11.mem
  /home/swaggo/Code/Fag/fag_project_tests/memory_init/sprite_init_54.mem
  /home/swaggo/Code/Fag/fag_project_tests/memory_init/backtile_init_20.mem
  /home/swaggo/Code/Fag/fag_project_tests/memory_init/sprite_init_43.mem
  /home/swaggo/Code/Fag/fag_project_tests/memory_init/sprite_init_4.mem
  /home/swaggo/Code/Fag/fag_project_tests/memory_init/sprite_init_86.mem
  /home/swaggo/Code/Fag/fag_project_tests/memory_init/tone_init_3.mem
  /home/swaggo/Code/Fag/fag_project_tests/memory_init/sprite_init_60.mem
  /home/swaggo/Code/Fag/fag_project_tests/memory_init/sprite_init_34.mem
  /home/swaggo/Code/Fag/fag_project_tests/memory_init/sprite_init_77.mem
  /home/swaggo/Code/Fag/fag_project_tests/memory_init/sprite_init_51.mem
  /home/swaggo/Code/Fag/fag_project_tests/memory_init/backtile_init_25.mem
  /home/swaggo/Code/Fag/fag_project_tests/memory_init/backtile_init_23.mem
  /home/swaggo/Code/Fag/fag_project_tests/memory_init/sprite_init_94.mem
  /home/swaggo/Code/Fag/fag_project_tests/memory_init/sprite_init_109.mem
  /home/swaggo/Code/Fag/fag_project_tests/memory_init/backtile_init_31.mem
  /home/swaggo/Code/Fag/fag_project_tests/memory_init/backtile_init_17.mem
  /home/swaggo/Code/Fag/fag_project_tests/memory_init/sprite_init_118.mem
  /home/swaggo/Code/Fag/fag_project_tests/memory_init/tone_init_5.mem
  /home/swaggo/Code/Fag/fag_project_tests/memory_init/sprite_init_100.mem
  /home/swaggo/Code/Fag/fag_project_tests/memory_init/sprite_init_17.mem
  /home/swaggo/Code/Fag/fag_project_tests/memory_init/backtile_init_7.mem
  /home/swaggo/Code/Fag/fag_project_tests/memory_init/sprite_init_26.mem
  /home/swaggo/Code/Fag/fag_project_tests/memory_init/sprite_init_126.mem
  /home/swaggo/Code/Fag/fag_project_tests/memory_init/sprite_init_69.mem
  /home/swaggo/Code/Fag/fag_project_tests/memory_init/sprite_init_75.mem
  /home/swaggo/Code/Fag/fag_project_tests/memory_init/tone_init_1.mem
  /home/swaggo/Code/Fag/fag_project_tests/memory_init/sprite_init_62.mem
  /home/swaggo/Code/Fag/fag_project_tests/memory_init/sprite_init_32.mem
  /home/swaggo/Code/Fag/fag_project_tests/memory_init/sprite_init_88.mem
  /home/swaggo/Code/Fag/fag_project_tests/memory_init/sprite_init_45.mem
  /home/swaggo/Code/Fag/fag_project_tests/memory_init/sprite_init_2.mem
  /home/swaggo/Code/Fag/fag_project_tests/memory_init/sprite_init_92.mem
  /home/swaggo/Code/Fag/fag_project_tests/memory_init/backtile_init_12.mem
  /home/swaggo/Code/Fag/fag_project_tests/memory_init/sprite_init_107.mem
  /home/swaggo/Code/Fag/fag_project_tests/memory_init/backtile_init_19.mem
  /home/swaggo/Code/Fag/fag_project_tests/memory_init/sprite_init_15.mem
  /home/swaggo/Code/Fag/fag_project_tests/memory_init/sprite_init_58.mem
  /home/swaggo/Code/Fag/fag_project_tests/memory_init/sprite_init_28.mem
  /home/swaggo/Code/Fag/fag_project_tests/memory_init/sprite_init_124.mem
  /home/swaggo/Code/Fag/fag_project_tests/memory_init/sprite_init_111.mem
  /home/swaggo/Code/Fag/fag_project_tests/memory_init/backtile_init_5.mem
  /home/swaggo/Code/Fag/fag_project_tests/memory_init/sprite_init_81.mem
  /home/swaggo/Code/Fag/fag_project_tests/memory_init/sprite_init_105.mem
  /home/swaggo/Code/Fag/fag_project_tests/memory_init/sprite_init_30.mem
  /home/swaggo/Code/Fag/fag_project_tests/memory_init/sprite_init_73.mem
  /home/swaggo/Code/Fag/fag_project_tests/memory_init/backbuffer_init1.mem
  /home/swaggo/Code/Fag/fag_project_tests/memory_init/sprite_init_12.mem
  /home/swaggo/Code/Fag/fag_project_tests/memory_init/sprite_init_123.mem
  /home/swaggo/Code/Fag/fag_project_tests/memory_init/sprite_init_14.mem
  /home/swaggo/Code/Fag/fag_project_tests/memory_init/backtile_init_2.mem
  /home/swaggo/Code/Fag/fag_project_tests/memory_init/tone_init_0.mem
  /home/swaggo/Code/Fag/fag_project_tests/memory_init/sprite_init_121.mem
  /home/swaggo/Code/Fag/fag_project_tests/memory_init/sprite_init_47.mem
  /home/swaggo/Code/Fag/fag_project_tests/memory_init/sprite_init_57.mem
  /home/swaggo/Code/Fag/fag_project_tests/memory_init/sprite_init_8.mem
  /home/swaggo/Code/Fag/fag_project_tests/memory_init/sprite_init_22.mem
  /home/swaggo/Code/Fag/fag_project_tests/memory_init/sprite_init_65.mem
  /home/swaggo/Code/Fag/fag_project_tests/memory_init/sprite_init_91.mem
  /home/swaggo/Code/Fag/fag_project_tests/memory_init/sprite_init_39.mem
  /home/swaggo/Code/Fag/fag_project_tests/memory_init/sprite_init_113.mem
  /home/swaggo/Code/Fag/fag_project_tests/memory_init/sprite_init_103.mem
  /home/swaggo/Code/Fag/fag_project_tests/memory_init/sprite_init_37.mem
  /home/swaggo/Code/Fag/fag_project_tests/memory_init/sprite_init_6.mem
  /home/swaggo/Code/Fag/fag_project_tests/memory_init/sprite_init_96.mem
  /home/swaggo/Code/Fag/fag_project_tests/memory_init/backtile_init_21.mem
  /home/swaggo/Code/Fag/fag_project_tests/memory_init/sprite_init_10.mem
  /home/swaggo/Code/Fag/fag_project_tests/memory_init/sprite_init_83.mem
  /home/swaggo/Code/Fag/fag_project_tests/memory_init/sprite_init_53.mem
  /home/swaggo/Code/Fag/fag_project_tests/memory_init/sprite_init_40.mem
  /home/swaggo/Code/Fag/fag_project_tests/memory_init/sprite_init_115.mem
  /home/swaggo/Code/Fag/fag_project_tests/memory_init/tone_init_7.mem
  /home/swaggo/Code/Fag/fag_project_tests/memory_init/sprite_init_55.mem
  /home/swaggo/Code/Fag/fag_project_tests/memory_init/sprite_init_19.mem
  /home/swaggo/Code/Fag/fag_project_tests/memory_init/sprite_init_49.mem
  /home/swaggo/Code/Fag/fag_project_tests/memory_init/sprite_init_98.mem
  /home/swaggo/Code/Fag/fag_project_tests/memory_init/sprite_init_71.mem
  /home/swaggo/Code/Fag/fag_project_tests/memory_init/sprite_init_85.mem
  /home/swaggo/Code/Fag/fag_project_tests/memory_init/backtile_init_0.mem
  /home/swaggo/Code/Fag/fag_project_tests/memory_init/backtile_init_28.mem
  /home/swaggo/Code/Fag/fag_project_tests/memory_init/backtile_init_9.mem
  /home/swaggo/Code/Fag/fag_project_tests/memory_init/backtile_init_15.mem
  /home/swaggo/Code/Fag/fag_project_tests/memory_init/sprite_init_67.mem
  /home/swaggo/Code/Fag/fag_project_tests/memory_init/sprite_init_24.mem
  /home/swaggo/Code/Fag/fag_project_tests/memory_init/sprite_init_18.mem
  /home/swaggo/Code/Fag/fag_project_tests/memory_init/sprite_init_127.mem
  /home/swaggo/Code/Fag/fag_project_tests/memory_init/sprite_init_119.mem
  /home/swaggo/Code/Fag/fag_project_tests/memory_init/tone_init_4.mem
  /home/swaggo/Code/Fag/fag_project_tests/memory_init/backtile_init_16.mem
  /home/swaggo/Code/Fag/fag_project_tests/memory_init/sprite_init_101.mem
  /home/swaggo/Code/Fag/fag_project_tests/memory_init/sprite_init_42.mem
  /home/swaggo/Code/Fag/fag_project_tests/memory_init/sprite_init_110.mem
  /home/swaggo/Code/Fag/fag_project_tests/memory_init/backtile_init_6.mem
  /home/swaggo/Code/Fag/fag_project_tests/memory_init/sprite_init_27.mem
  /home/swaggo/Code/Fag/fag_project_tests/memory_init/sprite_init_61.mem
  /home/swaggo/Code/Fag/fag_project_tests/memory_init/sprite_init_3.mem
  /home/swaggo/Code/Fag/fag_project_tests/memory_init/sprite_init_44.mem
  /home/swaggo/Code/Fag/fag_project_tests/memory_init/sprite_init_25.mem
  /home/swaggo/Code/Fag/fag_project_tests/memory_init/sprite_init_87.mem
  /home/swaggo/Code/Fag/fag_project_tests/memory_init/sprite_init_95.mem
  /home/swaggo/Code/Fag/fag_project_tests/memory_init/sprite_init_35.mem
  /home/swaggo/Code/Fag/fag_project_tests/memory_init/sprite_init_117.mem
  /home/swaggo/Code/Fag/fag_project_tests/memory_init/sprite_init_52.mem
  /home/swaggo/Code/Fag/fag_project_tests/memory_init/backtile_init_22.mem
  /home/swaggo/Code/Fag/fag_project_tests/memory_init/backtile_init_26.mem
  /home/swaggo/Code/Fag/fag_project_tests/memory_init/sprite_init_78.mem
  /home/swaggo/Code/Fag/fag_project_tests/memory_init/backtile_init_13.mem
  /home/swaggo/Code/Fag/fag_project_tests/memory_init/sprite_init_108.mem
  /home/swaggo/Code/Fag/fag_project_tests/memory_init/backtile_init_18.mem
  /home/swaggo/Code/Fag/fag_project_tests/memory_init/backtile_init_30.mem
  /home/swaggo/Code/Fag/fag_project_tests/memory_init/sprite_init_59.mem
  /home/swaggo/Code/Fag/fag_project_tests/memory_init/backtile_init_4.mem
  /home/swaggo/Code/Fag/fag_project_tests/memory_init/sprite_init_112.mem
  /home/swaggo/Code/Fag/fag_project_tests/memory_init/sprite_init_16.mem
  /home/swaggo/Code/Fag/fag_project_tests/memory_init/sprite_init_29.mem
  /home/swaggo/Code/Fag/fag_project_tests/memory_init/sprite_init_125.mem
  /home/swaggo/Code/Fag/fag_project_tests/memory_init/sprite_init_80.mem
  /home/swaggo/Code/Fag/fag_project_tests/memory_init/sprite_init_20.mem
  /home/swaggo/Code/Fag/fag_project_tests/memory_init/sprite_init_93.mem
  /home/swaggo/Code/Fag/fag_project_tests/memory_init/sprite_init_50.mem
  /home/swaggo/Code/Fag/fag_project_tests/memory_init/sprite_init_46.mem
  /home/swaggo/Code/Fag/fag_project_tests/memory_init/sprite_init_33.mem
  /home/swaggo/Code/Fag/fag_project_tests/memory_init/tone_init_2.mem
  /home/swaggo/Code/Fag/fag_project_tests/memory_init/sprite_init_76.mem
  /home/swaggo/Code/Fag/fag_project_tests/memory_init/sprite_init_1.mem
  /home/swaggo/Code/Fag/fag_project_tests/memory_init/sprite_init_89.mem
  /home/swaggo/Code/Fag/fag_project_tests/memory_init/backtile_init_24.mem
  /home/swaggo/Code/Fag/fag_project_tests/memory_init/backbuffer_init0.mem
  /home/swaggo/Code/Fag/fag_project_tests/memory_init/sprite_init_63.mem
  /home/swaggo/Code/Fag/fag_project_tests/memory_init/backtile_init_11.mem
  /home/swaggo/Code/Fag/fag_project_tests/memory_init/rotation45deg.mem
}
read_verilog -library xil_defaultlib {
  /home/swaggo/Code/Fag/fag_project_tests/RamInitSpWf.v
  /home/swaggo/Code/Fag/fag_project_tests/RamSpWf.v
  /home/swaggo/Code/Fag/fag_project_tests/Top.v
}
OPTRACE "Adding files" END { }
# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc /home/swaggo/Code/Fag/fag_project_tests/vivado/NexysA7Game/NexysA7Game.srcs/constrs_1/new/GameNexysA7-100T.xdc
set_property used_in_implementation false [get_files /home/swaggo/Code/Fag/fag_project_tests/vivado/NexysA7Game/NexysA7Game.srcs/constrs_1/new/GameNexysA7-100T.xdc]

set_param ips.enableIPCacheLiteLoad 1
close [open __synthesis_is_running__ w]

OPTRACE "synth_design" START { }
synth_design -top Top -part xc7a100tcsg324-1
OPTRACE "synth_design" END { }
if { [get_msg_config -count -severity {CRITICAL WARNING}] > 0 } {
 send_msg_id runtcl-6 info "Synthesis results are not added to the cache due to CRITICAL_WARNING"
}


OPTRACE "write_checkpoint" START { CHECKPOINT }
# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef Top.dcp
OPTRACE "write_checkpoint" END { }
OPTRACE "synth reports" START { REPORT }
generate_parallel_reports -reports { "report_utilization -file Top_utilization_synth.rpt -pb Top_utilization_synth.pb"  } 
OPTRACE "synth reports" END { }
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
OPTRACE "synth_1" END { }
